### ISSUE TITLE
Support `pacman.conf` `IgnorePkg` directive

### ISSUE THREAD

**Issue by D3SOX** [exequtic/apdatifier#10]
Packages that are configured to ignore updates are still shown in the applet

**Comment by exequtic** [comment]
Okay, I'll do it in the next version. Should I also add support for `IgnoreGroup`?

**Comment by D3SOX** [comment]
I've personally never used it but I guess it wouldn't hurt

**Comment by exequtic** [comment]
Do you have `pacman-contrib` installed? (`checkupdates`). And what wrapper are you using?
Only `checkupdates` and `yay` seem to respect `pacman.conf`, while others ignore it

```
~ ❯ pacman -Qu | wc -l
198

~ ❯ checkupdates | wc -l
118

~ ❯ yay -Qu | wc -l
124

~ ❯ paru -Qu | wc -l
205

~ ❯ trizen -Qu | wc -l
198
```

**Comment by D3SOX** [comment]
Yes I have `pacman-contrib` installed.
I'm using `paru` and I know it supports ignoring AUR packages via `pacman.conf` when upgrading (iirc `yay` does not)
