### ISSUE TITLE
Proposal to combine efforts into a new applet.

### ISSUE THREAD

**Issue by dhruv8sh** [exequtic/apdatifier#11]
Hi!
I'm the owner of the [Arch Update Checker](https://www.github.com/dhruv8sh/arch-update-checker).
I was wondering if you would be open to combining our efforts into something like a Plasmoid Updater, and similar things while making documentation for others to follow!
Maybe we could even create a superior Arch Update Applet!

**Comment by exequtic** [comment]
>a superior Arch Update Applet

I'm not sure. The current functionality that already exists probably suffices for the Plasmoid format. Anything more would lean towards a full-fledged application.
I've done almost everything I wanted, just a few things left.

>something like a Plasmoid Updater

Do you mean upgrading other plasmoids?
