### ISSUE TITLE
Option to use 'doas' instead of 'sudo' for wrapper

### ISSUE THREAD

**Issue by mohsunb** [exequtic/apdatifier#14]
Hello.

I am using 'doas' (opendoas) for root access on my system instead of 'sudo', and I have already configured 'paru' like that as well. However, it seems like the wrapper is hardcoded to use 'sudo', so I end up typing my password twice: once when the upgrade wrapper starts, and once again when 'paru' starts running. I'd really appreciate if I could somehow change this option.

By the way, thanks a lot for the work you do. I really love your plugin.

**Comment by mohsunb** [comment]
No, I don't have mirrorlist generation enabled.
![image](https://github.com/exequtic/apdatifier/assets/83220049/946ad134-f93f-46f4-9fd9-a0c600cfd211)

**Comment by exequtic** [comment]
Do I understand correctly that in order to avoid being prompted for the password twice, you need to execute `doas paru -Syu`, rather than just `paru -Syu`? I'm just not familiar with "doas"

**Comment by exequtic** [comment]
I just noticed in the screenshot that you have an old version. As far as I remember, it always runs `sudo mirrorlist_generator` before upgrade. Try installing the latest version 2.5.

**Comment by mohsunb** [comment]
I installed the plugin yesterday through Discover. Just checked and it still shows as v2.4. Though I did manage to download the latest one manually through browser. I will wait a while for updates and report if it fixed my issue. Thanks.

**Comment by exequtic** [comment]
Install latest version:
`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`

Also, if you need the mirrorlist generator, you can manually replace `sudo` with `doas` in the file: ~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/tools.js
line 107

**Comment by mohsunb** [comment]
After updating the plugin to v2.5, it is now fixed. Thanks for the help!
