### ISSUE TITLE
Option to generate mirrorlist every x updates

### ISSUE THREAD

**Issue by Whayme** [exequtic/apdatifier#15]
As the mirrorlist checker naturally takes a while to complete, it'd be very nice to be able to set it to only run every once in a while, whether that's defined by number of applied updates or simply on a user-defined timer.

Wonderful work, by the way, this is applet is wonderful.

**Comment by exequtic** [comment]
Hi! Good suggestion, but adding additional settings or a timer I think is unnecessary and complicated, so I simply added a question with `[y\N]`.
Now you can just press Enter to skip the mirror generation.

You can reinstall with latest commit. **it reset Apdatifier settings**
`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`

or you can download [tools.sh](https://github.com/exequtic/apdatifier/blob/main/package/contents/tools/tools.sh) and replace in `~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/`
This file may not be compatible with versions earlier than 2.5.

**Comment by Whayme** [comment]
After reinstalling as guided, it doesn't seem to prompt me or attempt to generate a mirrorlist at all, it just silently continues to run the update.  I made sure to re-enable the setting, of course.

**Comment by Whayme** [comment]
Works great, thank you!
