### ISSUE TITLE
I would like to translate the application into my language

### ISSUE THREAD

**Issue by dmaliog** [exequtic/apdatifier#16]
I would like to translate the application into my language, but I didn’t see the lang files.

**Comment by exequtic** [comment]
I will add support for other translations later.

**Comment by exequtic** [comment]
Done.

**Comment by dmaliog** [comment]
How can I now change the language in this widget?  I need Russian :)

**Comment by exequtic** [comment]
`sh ./build` will convert the `*.po` files to it's binary `*.mo` version and move it to `contents/locale/...`

so
```
cd ~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/translate/
sh ./build
```
and Log out or restart plasmashell

**Comment by dmaliog** [comment]
Thanks, all worked well!
