### ISSUE TITLE
Loading forever

### ISSUE THREAD

**Issue by mrhll** [exequtic/apdatifier#2]
Hi, this is not working for me on up to date Plasma Arch install - The loader ring turns forever.
Tried to install first with plasma widgets panel 'where I discovered it) then removed and installed the curl way from this git.
I tried playing with various settings and combinations but nothing changes. Any advise please ?
Witch complementary info can be helpful for you ?

PS. Any reason for providing installs on Fedora and Ubuntu for this ;)

**Comment by mrhll** [comment]
There is no output for both actually as system is up to date.
Will try it later and tell you - Thank you for your quick reply

**Comment by exequtic** [comment]
And still a loading indicator?

**Comment by mrhll** [comment]
Endlessly ...
![image](https://github.com/exequtic/apdatifier/assets/78020317/10061ea2-8219-4f10-8033-3141ca3aff78)

**Comment by exequtic** [comment]
> Why not simply ping archlinux.org for example and keep it simple ?
That's what I've done before. But I think it's a bad idea to ping a site, so I changed that way.

Please, can you copy tools.js file to ~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/ and restart widget. What will be in the notification?
[tools.tar.gz](https://github.com/exequtic/apdatifier/files/13964948/tools.tar.gz)

**Comment by mrhll** [comment]
![image](https://github.com/exequtic/apdatifier/assets/78020317/69700dc9-2ae9-4cb8-b491-69c15cc28873)

**Comment by exequtic** [comment]
Reinstall.
`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/KF5/package/contents/tools/tools.sh | sh -s install`

**Comment by mrhll** [comment]
Working !!
Thank you much !
![image](https://github.com/exequtic/apdatifier/assets/78020317/0119250f-4596-48fb-8c3d-293bec9d0ef9)
