### ISSUE TITLE
Update status should reset after an update finishes

### ISSUE THREAD

**Issue by Dungeonseeker** [exequtic/apdatifier#23]
Small bug but a bit annoying, after you run an update the icon shows there are still updates available until the next refresh (or you go and manually refresh). 

Would be great if after an update the icon goes back to normal automatically.

**Comment by exequtic** [comment]
> Small bug

This is not a bug. #22.
Alright, since you're the second person who needs this, I'll do it.

**Comment by exequtic** [comment]
@Dungeonseeker @kinoegit, I've added automatic update checks after a full system upgrade. You can test it.

**Comment by Dungeonseeker** [comment]
Just updated to the new version, seems great. I'll close this.

**Comment by kinoegit** [comment]
Thanks for implementing. However apdatifier keeps on being marked as outdated though I updated it manually several times

**Comment by exequtic** [comment]
> keeps on being marked as outdated

@kinoegit What do you mean? Where is it marked outdated?

**Comment by kinoegit** [comment]
Apdatifier keeps on counting itself as outdated. I git cloned v2.7 and copied com.github.exequtic.apdatifier/package to ~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier
BTW: reconfiguring apdatifier every time when updated is quite tedious, is there a way to restore the config (file)?

**Comment by exequtic** [comment]
@kinoegit Can you take a screenshot? Because if you go to `Settings > About` and see version `2.7-github`, that shouldn't be happening.

> reconfiguring apdatifier every time when updated

How do you update the widget, after which the settings are reset?

**Comment by kinoegit** [comment]
![00](https://github.com/exequtic/apdatifier/assets/18682867/9d303bc4-dfff-4029-9dbb-15bb249e7001)
since I can't update plasmoids via right-click "add plasmoids" because of an error: _file already exists,_ I either have to manually replace the old folder with the downloaded current one or right-click "add plasmoids" and uninstall apdatifier first and then reinstall it

**Comment by exequtic** [comment]
@kinoegit, Just try reinstall with this command:

`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`

**Comment by kinoegit** [comment]
Thanks for the curl command, it works. But update score is still 1 for apdatifier itself...

**Comment by exequtic** [comment]
@kinoegit, I don't know why it appears in the list... Try deleting the `~/.cache/apdatifier` directory and then Log Out or restart.

**Comment by kinoegit** [comment]
Thanks for your kindly help, but neither `rm -r ~/.cache/apdatifier` nor editing `~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/metadata.json` and changeing version `2.7-github` to `2.7` and a restart did work. 
Still apdatifier itself is counted as outdated. 
Will wait til the next release maybe that does fix things...

**Comment by exequtic** [comment]
@kinoegit, To ensure this isn't in the next version, we need to understand the problem and fix it :)
My last request:
1) Download it again using the curl command above (I pushed new changes). Then Log Out - Log In and check for updates.
2) If after step 1 the widget is still on the list, what versions in the extended view?

**Comment by kinoegit** [comment]
> ![00](https://private-user-images.githubusercontent.com/18682867/339516086-9d303bc4-dfff-4029-9dbb-15bb249e7001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTI0NzUsIm5iZiI6MTcxODMxMjE3NSwicGF0aCI6Ii8xODY4Mjg2Ny8zMzk1MTYwODYtOWQzMDNiYzQtZGZmZi00MDI5LTlkYmItMTViYjI0OWU3MDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDIwNTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZmUxM2VhODRjYzlmMjgxZjRlY2ZiOWJhYTdiZDUwZWU1MmI0ZDVhOTQwYzU0OGFhNzQzNGVlYmFlYTBjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wnkHprhZ3HqJrCZIyDAYTCp-j77S-uBW82-9rRg9Pw) 

After step 1 the widget is still on the list. And Version is `2.7`, as in the image...

**Comment by Dungeonseeker** [comment]
Yeah, I don't have this issue at all. For reference 
![Screenshot_20240614_102545](https://github.com/exequtic/apdatifier/assets/15569173/38ae6eff-f04b-460b-a62c-6622378ca195)

**Comment by kinoegit** [comment]
I did wipe all apdatifier traces I could find and reinstalled it with the command: `curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`.
Finally apdatifier widget isn't in the update list anymore! Even though the version is still `2.7` not `2.7-github`. I wonder how to install the `-github` version and what is the difference in the first place?

**Comment by exequtic** [comment]
> Even though the version is still 2.7 not 2.7-github

@kinoegit, Because I removed `-github` from the version number yesterday. Ignore that.
