### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by kinoegit** [exequtic/apdatifier#25]
[template.txt](https://github.com/user-attachments/files/15842708/template.txt)
100% done, maybe some translations will need revision...
I still don't know how to make a pull request...

**Comment by exequtic** [comment]
> 100% done

No. 5 strings with the plural form are not translated. Is this your translation?

**Comment by kinoegit** [comment]
[de.txt](https://github.com/user-attachments/files/15844676/de.txt)
I overlooked those plurals. Now it should be completed.
> Is this your translation?
Positive

**Comment by exequtic** [comment]
Thanks, I will include your translation in the next version.

> maybe some translations will need revision

If you decide to revise the translation, attach it here in this issue
