### ISSUE TITLE
Ignore a package from being upgraded

### ISSUE THREAD

**Issue by Mshmaitelly** [exequtic/apdatifier#29]
I have a mesa-git, and when I am upgrading from 24.2-dev to 24.3-dev, my system does not boot into a graphical mode.
Thus, I would like to add "mesa-git" to an ignore list. How can I do that?

**Comment by exequtic** [comment]
To ignore a package from being upgraded, open /etc/pacman.conf, find the [options] section, and add or edit the IgnorePkg line to include mesa-git.

[Arch Wiki](https://wiki.archlinux.org/title/Pacman#Skip_package_from_being_upgraded)

**Comment by Mshmaitelly** [comment]
Resolved.
Thanks a lot.
