### ISSUE TITLE
multiplexed msgid causing translation difficulties

### ISSUE THREAD

**Issue by CEllenvia** [exequtic/apdatifier#30]
First of all, thanks for making such an useful plasma widgets!
---
We're translating this widget into simplified Chinese. Most of work is completed, but the ```msgid "update is pending"``` caused translation difficulty, which caused by expression difference in Chinese.

- the ```../contents/ui/configuration/Appearance.qml``` one should be translated with ```msgid "Shown when"``` and the whole sentence should be “当有_个更新被挂起时显示”
- the ``` ../contents/tools/tools.js``` one should be translated separately: "_个更新被挂起"

these translations cant be multiplexed in Chinese, since we seldom use passive voice.

Thanks again for making it, and hope we can deal with it soon! :)

**Comment by exequtic** [comment]
So the problem is that the same translation string is used in two different contexts? If I create separate translation strings for each, will that solve the issue?

**Comment by CEllenvia** [comment]
> So the problem is that the same translation string is used in two different contexts? If I create separate translation strings for each, will that solve the issue?

Yeah, that solves the problem. we'll make the translation available soon. Thanks!
