### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by shadowshard4080** [exequtic/apdatifier#31]
This happens when I enable searching the AUR?
![image](https://github.com/user-attachments/assets/2d07ae61-934c-4502-93fd-d080e0aada0e)

**Comment by exequtic** [comment]
This is not a widget issue, but an issue with yay. [Try rebuilding it](https://github.com/Jguer/yay/issues/1519).

**Comment by shadowshard4080** [comment]
Thanks. That solved the issue.
