### ISSUE TITLE
Feature suggestion:  Execution an update, total time

### ISSUE THREAD

**Issue by Mshmaitelly** [exequtic/apdatifier#32]
I suggest presenting the total time of the execution of an update.

**Comment by exequtic** [comment]
Do you mean estimating how long the upgrade will take, or simply showing how long the current upgrade has been running?

**Comment by Mshmaitelly** [comment]
When doing a yay --noconfirm my zshell uses thefollowing oh-my-zsh plugin
It would output the total execution time for the last upgrade (or any command) completed

https://github.com/popstas/zsh-command-time

**Comment by Mshmaitelly** [comment]
I am very impressed with the progress of this fantastic app. Best luck for you.
Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Nov 23, 2024 at 1:31 AM, ***@***.***> wrote:   


Closed #32 as completed.
