### ISSUE TITLE
Feature Request: Showing updates in custom repositories

### ISSUE THREAD

**Issue by MJ-asa** [exequtic/apdatifier#33]
I have the Chaotic AUR and Liquorix repos and I would love to be able to see updates from them! Apologies if this is already implemented :3 Thank uuu!

**Comment by exequtic** [comment]
The widget should show updates from other repositories, for example:

ALHP
![Screenshot_20240904_001417](https://github.com/user-attachments/assets/25963a92-7229-4ccc-9d98-690d0126126b)


CatchyOS
![326929306-7e028007-0aaf-41ca-897f-1d97cb858176](https://github.com/user-attachments/assets/11585899-ec99-4dba-9485-967cd17a0788)

ChaoticAUR
![Captura de pantalla_20240615_105524](https://github.com/user-attachments/assets/b00b4585-cf74-44fa-8da3-8c0ec73307e4)
