### ISSUE TITLE
Feature suggestion: On 4K monitors, fonts are too small, scaling up the widget for high DPI monitors

### ISSUE THREAD

**Issue by Mshmaitelly** [exequtic/apdatifier#35]
My aging eyes not getting any better, I have to click on the app icons with a leap of faith.
Kindly, I suggest the whole widget add a slide with a scaling factor that would enlarge the app menus by said factor.

**Comment by exequtic** [comment]
I can't just change the scale in QML like that.
The font size depends on the font settings in the system settings, just like in all standard KDE widgets, for example, NetworkManager.
If the font in the widget is small, does that mean everything in the system is too small? Then you need to increase the `Display Configuration > Scale` in the system settings and increase the `General Font` size.

![Screenshot_20240903](https://github.com/user-attachments/assets/9462fe9b-f295-4eff-99c3-2304c95a3b1d)

**Comment by Mshmaitelly** [comment]
Fantastic, I will try that, and report back.
