### ISSUE TITLE
Won't launch console anymore, so I can't update or use Management

### ISSUE THREAD

**Issue by QuarkZ26** [exequtic/apdatifier#36]
Hello,

Not sure why but some days ago, this widget broke where clicking on update just won't launch the console, so it spins, then goes back to listing packages.
I have reinstalled and cleared the settings to no avail.
I also tried to switch from konsole to xterm.

**Comment by exequtic** [comment]
Try reinstall with the **latest commit**.

`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`

**Comment by QuarkZ26** [comment]
Still doesn't work. Are there any other files that I should try and clear?

**Comment by exequtic** [comment]
No. Just reinstall with the latest commit (changes in the files `tools.js` and `tools.sh`), and it’s preferable to restart plasmashell or log out. Have you tried any other terminal besides Konsole and xterm?

**Comment by QuarkZ26** [comment]
Well, restarting Plasma actually did the trick, appreciate the help!
