### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by JasonCraneAdkins** [exequtic/apdatifier#37]
Hi,

is there CLI support or is this a planed feature?
I use an Alias to update my System, it would be nice if i could ad a command to update Apdatifier afterwards

**Comment by exequtic** [comment]
Yes, I was thinking of doing something to make it work without the KDE widget, but at the moment I don't have any time for that. Currently (with the latest commit), you can call some functions from a bash script and create aliases like this, for example:
 
```
apdatifier="$XDG_DATA_HOME/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/tools.sh"
alias management='$apdatifier management'
alias updMirrors='$apdatifier mirrorlist'
alias updWidgets='$apdatifier upgradeAllWidgets'

# Full upgrade: refresh mirrorlist, system updates, flatpak apps, kde widgets
alias upgrade='updMirrors; yay; flatpak update; updWidgets'
```

**Comment by UserCel** [comment]
I would also appreciate such a feature, it would be nice to at least be able to refresh/clear the packages in the plasmoid after a system upgrade using a pacman hook.

Thanks for your efforts of this!
