### ISSUE TITLE
Icons gones

### ISSUE THREAD

**Issue by claymorwan** [exequtic/apdatifier#38]
For some reason some of the icons died, I did try to reinstall and reboot my computer but nothing
![image](https://github.com/user-attachments/assets/5b7abfaf-c1e6-472c-8458-5ee2f76eb827)
![image](https://github.com/user-attachments/assets/83a18074-3002-4d4b-ad8b-c676264e01dc)

**Comment by exequtic** [comment]
These icons should be located in the path `$HOME/.local/share/icons/breeze/status/24/`. Do you have these files? (apdatifier-*.svg)

**Comment by claymorwan** [comment]
Yep I do have them

**Comment by exequtic** [comment]
Are these icons available in the icon selection window? (You can open this window through Apdatifier settings -> Rules)

**Comment by claymorwan** [comment]
I'm not really sure, tho I don't have it in the Appearence tab
![image](https://github.com/user-attachments/assets/da73acc0-8399-4c09-b86f-1f3c34f69132)
![Screenshot_20240906_164135](https://github.com/user-attachments/assets/f46d63cc-3c34-493d-b005-519a090e4206)

**Comment by exequtic** [comment]
I mean in this window:
![Screenshot_20240906_194616](https://github.com/user-attachments/assets/33c49ec4-3c5c-4a06-85e9-deb4e7e66010)

**Comment by claymorwan** [comment]
Nothing
![Screenshot_20240906_165214](https://github.com/user-attachments/assets/990d514a-c5f7-49ec-afdf-70117cf17df0)

**Comment by exequtic** [comment]
Change to **All**

**Comment by claymorwan** [comment]
O sorry I lol, but yeah still nothing
![Screenshot_20240906_165704](https://github.com/user-attachments/assets/948c4367-81cd-4386-b08a-d2eb3ee3ef46)

**Comment by exequtic** [comment]
Well, they should be there, but for some reason, they’re not. It might be that the icon cache isn’t updating—I’m not sure why. Try switching the icon theme to Breeze or moving the icons to a different location, like into the directory with your icon theme.

**Comment by claymorwan** [comment]
I copied the files to my themes directory and it seems to be working now, it do be weird cuz it used to work. I think it broke when I logged into wayland instead of X tho if that helps. But thanksu for the help :3
