### ISSUE TITLE
the toolbar icons are hidden by another icon

### ISSUE THREAD

**Issue by Cherkah** [exequtic/apdatifier#42]
see bellow:

![screenshot_14 10 24_23h51](https://github.com/user-attachments/assets/221c3859-005b-49ff-9ffc-e337bd9719b6)

on the screenshot there are only two icons affected but it affects all the icons in the toolbar (if selected in settings).

PS: thanks for this wonderful plamoid (efficient and discreet....). it deserves a coffee ;) . I don't know if themes downloaded via store.kde.org can be updated like widgets via a metadata.json file?!! if it is the case (confirmation), I will submit the idea to the 2 theme creators that I use so that they can think about this improvement

regards

**Comment by exequtic** [comment]
This issue was fixed in version 2.8.1.

![Screenshot_20241015_183434](https://github.com/user-attachments/assets/76682bdb-9ee3-4f7a-8a33-fa4ea6d8542a)

> I don't know if themes downloaded via store.kde.org can be updated like widgets via a metadata.json file?!!

Although this won't differ much from updating the widgets and only requires small changes in the code, I don't like my current implementation; it needs improvements or a completely different approach.
Additionally, content creators often don't properly format their packages, which means they can't simply be installed via kpackagetool. For example, they might just upload an archive with a theme that needs to be copied manually.
Therefore, I don't plan to add anything other than widgets for now.

**Comment by Cherkah** [comment]
I also think that since the management of themes is not the same as that of widgets, the thing would not be possible.

concerning the issue, apdatifier was updated yesterday 
![screenshot_15 10 24_22h48-1](https://github.com/user-attachments/assets/7fd6e10b-c047-4e02-be80-708bb82fec87)


but the plasmoid remains at version 2.8:
![screenshot_15 10 24_22h48](https://github.com/user-attachments/assets/76c73eca-0030-4772-91e3-d32b659db351)

**Comment by exequtic** [comment]
Remove the widget and install it again. I discovered a bug today: if you upgrade it through Apdatifier, version 2.8 is downloaded instead of 2.8.1 (yes, it will display as 2.8.1).

**Comment by Cherkah** [comment]
Remove the widget and install it again did the trick.

I observed 2 small issues:
A) the instances of the widget do not seem to be synchronized
B) an update announced by apdatifier and carried out via the terminal (or other) does not modify the state of the widget. you have to synchronize each instance individually

regards

**Comment by exequtic** [comment]
You mean more than one running widget? But why would you need more than one?

**Comment by Cherkah** [comment]
> You mean more than one running widget?
yes 

> But why would you need more than one?

i dont need more widget, but i have two screens : the first one has two pannel (each of them with one miniature box) and the second one with one pannel (miniature box)

apdatifier as widget appears in each pannel.

**Comment by exequtic** [comment]
> i dont need more widget

If you don't need more than one widget, you can simply disable it in the system tray settings

**Comment by exequtic** [comment]
Ok, now it’s clear.

> A)

I have an idea on how to implement this, but I can't promise anything yet.

> B)

I plan to do this, but probably not anytime soon.

**Comment by Cherkah** [comment]
no problem, In any case, the widget is very successful.
the 2 points raised (A & B) will be improvements in visual consistency
