### ISSUE TITLE
Plasmoids update checks just loops forever

### ISSUE THREAD

**Issue by claymorwan** [exequtic/apdatifier#49]
I installed all the required package, but for some reason it just checks forever, which is weird cuz it's working just find on my laptop.
![image](https://github.com/user-attachments/assets/90fd0c4c-247e-422b-9d51-8c2911f5fe6b)

**Comment by exequtic** [comment]
What's the output when running this command?

`$HOME/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/tools.sh checkWidgets`

**Comment by exequtic** [comment]
The updates check script itself is working, so the error might be elsewhere.
1) Keep only the "Plasma Widgets" check enabled in the settings
2) Run 'watch journalctl --user-unit=plasma-plasmashell.service --reverse'
3) Start the updates check
4) Look for any errors related to Apdatifier in the log

**Comment by claymorwan** [comment]
this is the kinda output i get
![Screenshot_20241108_175709](https://github.com/user-attachments/assets/18859971-04d7-42dd-a78f-f61f377c0756)

**Comment by exequtic** [comment]
Fixed. You can install the git version to test:

```
git clone https://github.com/exequtic/apdatifier.git
kpackagetool6 -t Plasma/Applet -u apdatifier/package
```

Then Log Out.
Or restart plasmashell: `systemctl --user restart plasma-plasmashell.service`

**Comment by claymorwan** [comment]
O it's working now thanks
btw while I'm there, how did u get the aur package to have icons in the plasmoid's menu ? Or is it supposed to do it and is broken

**Comment by exequtic** [comment]
> how did u get the aur package to have icons in the plasmoid's menu ? Or is it supposed to do it and is broken

Have you tried adding icon rules in the Apdatifier settings?

**Comment by claymorwan** [comment]
O so I gotta add a rule icon for each package got it, thanks :3
