### ISSUE TITLE
Apdatifier is not compatible with Plasma 6

### ISSUE THREAD

**Issue by jdfhtx** [exequtic/apdatifier#5]
Post install on Plasma6, a warning appears:

This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. Please contact the widget's author for an updated version.

![Screenshot_20240307_112102](https://github.com/exequtic/apdatifier/assets/31213349/8d5307a3-2cfc-4dbb-99ab-105754c9c888)

**Comment by exequtic** [comment]
New version for Plasma 6 [here](https://github.com/exequtic/apdatifier/tree/main). I just ported it today, let me know if it works for you.

**Comment by jdfhtx** [comment]
Thanks for such a quick response. 

This version seems to work great!
