### ISSUE TITLE
Añadir traducciones para el idioma Español / Add translations for the Spanish language

### ISSUE THREAD

**Issue by RodvinSanchez** [exequtic/apdatifier#50]
This issue includes the Spanish translations for the project. I have filled out the es.po file with all the necessary translations. Please review the changes and merge them if everything is correct.

[sp.txt](https://github.com/user-attachments/files/17783252/sp.txt)

**Comment by exequtic** [comment]
Thank you for the translation! It looks like everything is fine. In the next release, there will be new lines to translate. I'll update the template and add your translation a bit later, and you'll be able to complete it. I'll inform you about this.

**Comment by exequtic** [comment]
You can complete the translation ([this file es.po](https://github.com/exequtic/apdatifier/blob/main/package/translate/po/es.po))

**Comment by RodvinSanchez** [comment]
[sp2024-12.txt](https://github.com/user-attachments/files/18016423/sp2024-12.txt)
Spanish translation, for the new entries in the language file.

**Comment by RodvinSanchez** [comment]
I have updated the language file to Spanish.

[es.txt](https://github.com/user-attachments/files/20466971/es.txt)
