### ISSUE TITLE
Count doesn't work when News is enabled and there are no new news

### ISSUE THREAD

**Issue by luisbocanegra** [exequtic/apdatifier#7]
Steps to reproduce:
1. Enable **Arch Linux News**
2. Check for updates from the widget
3. Status bar shows exit code 1 and stops there without checking for Arch/AUR news

```
paru -Pw
no new news
1 ❎ 1.316s 17:27 ~
```
![Screenshot_20240330_173059](https://github.com/exequtic/apdatifier/assets/15076387/6f1b63fc-e7d8-4af4-8973-cb5e4b327fe2)

**Comment by exequtic** [comment]
Strange. For me, paru -Pw always displays the latest news. I can't reproduce the output of "no new news".

**Comment by luisbocanegra** [comment]
I think is because I have `NewsOnUpgrade` option enabled in paru. News are shown when upgrading and discarded after.
Maybe this is saved somewhere and that's probably why `-Pw` shows no news?

**Comment by exequtic** [comment]
I've changed the function, it should work now. Give it a try.

**Comment by luisbocanegra** [comment]
It works now. Thank you
