### ISSUE TITLE
Custom icon matching ideas

### ISSUE THREAD

**Issue by luisbocanegra** [exequtic/apdatifier#8]
I would like to have icons for all the packages :) but find the icon matching very limited :(
Could it be possible/feasible to match package custom icons with rules in the following order?
1. Per repository (core, extra, aur...)
2. Per package group (plasma, gnome, kf6...)
3. Per pattern e.g. python-.* (python modules, haskell, *.-git...)

**Comment by exequtic** [comment]
Good idea! I'll take note of that.

**Comment by exequtic** [comment]
How about this? In this order:

1) First set icons for repositories
2) Set icons for groups
3) Set icons based on name matching
4) Set individual icon with exact name match

Each overrides the previous icon. For example, 'krunner5' in the AUR repository and in the plasma group - will use the second icon. The same goes for octopi.

```bash
curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install
```
![Screenshot_20240331_162131](https://github.com/exequtic/apdatifier/assets/29355358/09f75583-e22e-4d12-8eb4-9e0b211883e3)

**Comment by luisbocanegra** [comment]
Thank you, it works as expected. Very well done!
