### ISSUE TITLE
24 updates pending, but nothing to update

### ISSUE THREAD

**Issue by Mshmaitelly** [exequtic/apdatifier#9]
24 updates are pending, However, when I do system update, nothing to be updated.

**Comment by exequtic** [comment]
When you press 'Upgrade system', does the terminal open? What output does the terminal display?

**Comment by Mshmaitelly** [comment]
1, Yes
2. Konsole
3. Normal yay --nocomfirm execution and nothing is found to be upgraded.

Update: The issue got resolved by itself. Back to normal behavior. Could it be an issue with the pacman mirror site?

Please, you can mark this as resolved/rejected. 
Thanks

**Comment by exequtic** [comment]
It's possible that you had a previous version installed and didn't perform a logout or restart of plasmashell as stated in the README, so the plasmoid may work with errors.
In any case, thank you for reporting the issue. I won't close it for now. It's possible that someone else may encounter the same issue.
